services:
  # Back-end da aplicação
  tekveiculos:
    build: .
    ports:
      - '8081:8080'
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:${DB_PORT}/database
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  # Banco de dados (PostgreSQL)
  database:
    container_name: databasetekveiculos
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgAdmin para gerenciar o PostgreSQL
  pgadmin:
    container_name: pgtekveiculos
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8082:80'
    depends_on:
      - database

volumes:
  pgdata: {}